table fMetas
	lineageTag: 0ec7c232-5bfe-41a6-9e78-b7b760f10704

	column 'Código Vendedor'
		dataType: int64
		formatString: 0
		lineageTag: 884a46d8-9987-4263-b674-f885421ccb19
		summarizeBy: none
		sourceColumn: Código Vendedor

		annotation SummarizationSetBy = Automatic

	column 'Valor Meta'
		dataType: double
		lineageTag: 10f2c5cd-00a3-430c-800f-ab1270eaeb11
		summarizeBy: sum
		sourceColumn: Valor Meta

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Data
		dataType: dateTime
		formatString: Long Date
		lineageTag: fc830cfc-9402-42be-ada5-5d18ab97eb9c
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition fMetas-8c75f9a5-9347-4673-8b5a-7bff5fea51e5 = m
		mode: import
		queryGroup: Fatos
		source =
				let
				    Fonte = Excel.Workbook(File.Contents(#"Diretório Base de Dados" & "\Base de Dados.xlsx"), null, true),
				    Metas_Sheet = Fonte{[Item="Metas",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Metas_Sheet, [PromoteAllScalars=true]),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Cabeçalhos Promovidos",{"Vendedor"}),
				    #"Outras Colunas Não Dinâmicas" = Table.UnpivotOtherColumns(#"Colunas Removidas", {"cdVendedor"}, "DataMeta", "ValorMeta"),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Outras Colunas Não Dinâmicas",{{"cdVendedor", Int64.Type}, {"DataMeta", type date}, {"ValorMeta", type number}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado",{{"ValorMeta", "ValorMeta1"}}),
				    #"Mês Inserido" = Table.AddColumn(#"Colunas Renomeadas", "Mês", each Date.Month([DataMeta]), Int64.Type),
				    #"Ano Inserido" = Table.AddColumn(#"Mês Inserido", "Ano", each Date.Year([DataMeta]), Int64.Type),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Ano Inserido", {"Mês", "Ano"}, dCalendario, {"Mês", "Ano"}, "dCalendario", JoinKind.LeftOuter),
				    #"dCalendario Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "dCalendario", {"Data", "Dias do Mês"}, {"Data", "Dias do Mês"}),
				    #"Divisão Inserida" = Table.AddColumn(#"dCalendario Expandido", "ValorMeta", each [ValorMeta1] / [Dias do Mês], type number),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Divisão Inserida",{"cdVendedor", "Data", "ValorMeta"}),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Outras Colunas Removidas",{{"cdVendedor", "Código Vendedor"}, {"ValorMeta", "Valor Meta"}})
				in
				    #"Colunas Renomeadas1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

